benchmark: libero_spatial
num_trails_per_task: 50
num_steps_wait: 10
seed: 7
base_url: http://localhost:7891
replan_step: 5

send_state: true
send_image:
- image
- wrist_image

output_dir: "results/example_pi0_libero_spatial"